### ISSUE TITLE
error running Viya 3.5 pre-install-playbook

### ISSUE THREAD

**Issue by onion1984** [sassoftware/viya-ark#26] opened 2019-11-26 09:26 UTC
Hi, I ran into the following error while running the Viya 3.5 pre-install-playbook

TASK [viya-ark.preinstall : Ping host postgres1 from deployment host using gathered shortname] *******************************************************************
fatal: [deployTarget]: FAILED! => {"msg": "The conditional check 'hostname_results.stdout_lines | length > 0' failed. The error was: error while evaluating conditional (hostname_results.stdout_lines | length > 0): 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'pre_short_hostname_check_results'\n\nThe error appears to have been in '/home/ec2-user/viya-ark-Viya35-ark-1.0/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.short_hostname_check_loop.yml': line 2, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:\n    - name: \"Ping host {{ host }} from deployment host using gathered shortname\"\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}

**Comment by erharb** [comment] 2019-11-26 15:03
@onion1984 what version of Ansible were you using? Supported range is 2.7.x through 2.9.x

**Comment by onion1984** [comment] 2019-11-26 15:12
@erharb I was using Ansible 2.7.x
I am doing a multi machine deployment. I don't have a DNS in my environment, so I configured the hosts file on all the machines. Could that be the reason?

**Comment by erwangranger** [comment] 2019-11-26 15:35
The variable that seems to have no value  (pre_short_hostname_check_results)  should have been set in [this task](https://github.com/sassoftware/viya-ark/blob/a5f01b928b8aba3bab965ab4d1f0e21a89fa9705/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.short_hostname_check.yml#L10). 

Do all you machines return a value when you run 
```bash 
ansible all -m shell -a "hostname -s"
```
 ?
Or, are you running only a subset of the playbook, maybe with tags or skip-tags, something that would have prevented this task to run?

**Comment by onion1984** [comment] 2019-11-27 01:24
@erwangranger hi erwan, I am running the entire pre-install-playbook. 
Here is the result if i ran ansible all -m shell -a "hostname -s"

deployTarget | CHANGED | rc=0 >>
microservices

postgres1 | CHANGED | rc=0 >>
postgres1

postgres3 | CHANGED | rc=0 >>
postgres3

postgres2 | CHANGED | rc=0 >>
postgres2

**Comment by erharb** [comment] 2019-12-02 21:46
@onion1984 can you provide the full ansible-playbook command you invoked to achieve the original error? It may also help to run with full verbosity (-vvvv) and attach the resulting log here.

**Comment by AlissaSchleich** [comment] 2019-12-04 20:08
@onion1984  Did you get past the error?   We are trying to determine if there is an environment issue or code issue.  Can you send us the full verbose log and ansible-playbook command please.

**Comment by onion1984** [comment] 2019-12-05 02:29
@AlissaSchleich @erharb sorry for the late reply. I used the skip-tag to bypass the hostname -s check and completed the pre-installation playbook. And I didn't encounter any issue during SAS Viya 3.5 deployment. The original environment was purged as I was using AWS sandbox.
I tried to replicate the error again by creating a new environment today. But this round, I am able to finish the pre-installation playbook without any error. so I think we can close this issue for now

**Comment by kevinlinglesas** [comment] 2019-12-05 05:10
Thanks for the feedback @onion1984.   If this issue re-surfaces please let us know.

**Comment by henriquevaskys** [comment] 2020-05-05 00:36
Hi folks. I have this issue on a OpenStack envionment I created - I can forward you the test environment details on a separate email.

hostname -s commands runs as follow:

`[cloud-user@USER-COMPANY-ansible pre-install-playbook]$ ansible all -i pre-install.inventory.ini -m shell -a "hostname -s"
deployTarget | CHANGED | rc=0 >>
USER-COMPANY-viya
casTarget | CHANGED | rc=0 >>
USER-COMPANY-cas
`
My inventory file is like the below:

`## This is a sample inventory which contains all possible host groups.
## You should replace this with the actual inventory that comes with the SAS Viya Deployment playbook
## if you have one available.

## This line defines the local Ansible Controller machine.
##    (are you sure it needs to have the pre-reqs applied to it?)
deployTarget ansible_host=USER-COMPANY-viya.local ansible_user=cloud-user ansible_ssh_private_key_file=/opt/sas/USER-key.p
em
casTarget    ansible_host=USER-COMPANY-cas.local ansible_user=cloud-user ansible_ssh_private_key_file=/opt/sas/USER-key.pe
m



## This line would define another (not local) machine.
## Note that the _user and _key parameters are not mandatory,
##   * if you remain the same user,
##   * and the ssh keys are already defined in the right location (~/.ssh/id_rsa)
# deployTarget02 ansible_host=<machine_address> ansible_user=<userid> ansible_ssh_private_key_file=<keyfile>

[sas_all]
deployTarget
casTarget
`

Running the playbook with -vvvv option
[deployment.log](https://github.com/sassoftware/viya-ark/files/4578421/deployment.log)

What I found interesting is if I comment the second host in the inventory file, the playbook runs fine. Then, if I comment the first one and uncomment the second, the playbook also runs fine.

Thanks,
Henri

**Comment by kevinlinglesas** [comment] 2020-05-06 16:45
Will reopen and investigate.  Thanks, @henriquevaskys for the info.

**Comment by kevinlinglesas** [comment] 2020-05-22 18:31
@henriquevaskys , sorry for the delay.  I am working on reproducing your findings based on the environment information you sent by email.   Please keep that environment around awhile longer.

**Comment by kevinlinglesas** [comment] 2020-05-22 20:29
@henriquevaskys, i didn't see it mentioned (don't think I missed it ;) exactly how you invoked the pre-install playbook.   Can you recall what that invocation signature was?

I find that skip-tags are needed to get past memory, cores & and storage deficiencies in casTarget.    Without those skip-tags, the playbook will fail in addition to the failure related to short hostname.   With those skip-tags,  or if the playbook is executed with just the short_hostname_check tag, I see no failure.

**Comment by henriquevaskys** [comment] 2020-05-25 02:19
Hi @kevinlinglesas no worries :)
The environment is still up, I'll add a note to my colleagues to not delete it.

Unfortunately my CAS Server is quite small (only need that environment for testing). To avoid using skip-tags, I changed roles/viya-ark.preinstall/defaults/main.yml  to  min_mem_mb: 800 and rerun it - which failed again with same behavior:

````
[cloud-user@sbrhel-medibank-ansible pre-install-playbook]$ ansible-playbook -i pre-install.inventory.ini viya_pre_install_playbook.yml --check
(...)
TASK [viya-ark.preinstall : set_fact] ****************************************************************************************************************************************************
skipping: [viyaTarget]

TASK [viya-ark.preinstall : Ping host casTarget from deployment host using gathered shortname] *******************************************************************************************
fatal: [viyaTarget]: FAILED! => {"msg": "The conditional check 'hostname_results.stdout_lines | length > 0' failed. The error was: error while evaluating conditional (hostname_results.stdout_lines | length > 0): 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'pre_short_hostname_check_results'\n\nThe error appears to be in '/opt/sas/sas_viya_playbook/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.short_hostname_check_loop.yml': line 6, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:\n    - name: \"Ping host {{ host }} from deployment host using gathered shortname\"\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}

TASK [viya-ark.preinstall : debug] *******************************************************************************************************************************************************
fatal: [viyaTarget]: FAILED! => {"msg": "The conditional check 'hostname_results.stdout_lines | length > 0' failed. The error was: error while evaluating conditional (hostname_results.stdout_lines | length > 0): 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'pre_short_hostname_check_results'\n\nThe error appears to be in '/opt/sas/sas_viya_playbook/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.short_hostname_check_loop.yml': line 13, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  rescue:\n    - debug:\n      ^ here\n"}
````

Running with the skip-tags short_hostname_check worked. But I found out it fails (and don't complete al checks) for hosts which doesn't meet the minimum CPU. Should I open another Issue for this (I think I heard this would print the error but won't prevent other checks to run)?

**Comment by erharb** [comment] 2020-05-26 12:56
pre_short_hostname_check_results is registered by the results of the command "hostname -s"

https://github.com/sassoftware/viya-ark/blob/master/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.short_hostname_check.yml#L14

```
- block:
    - name: "Gather short hostname"
      command: "hostname -s"
      check_mode: no
      changed_when: false
      register: pre_short_hostname_check_results
```

The only way that value would not be set would be due to using check mode. Can you confirm if you used ansible check mode? Also can you provide what shows in the log for TASK name "Gather short hostname"?

**Comment by henriquevaskys** [comment] 2020-06-01 00:13
Hi @erharb . On both --check and normal mode it fails.
Please check my update here for full log: https://github.com/sassoftware/viya-ark/issues/26#issuecomment-623781076

**Comment by sasjowood** [comment] 2020-06-01 16:16
Hey @henriquevaskys,

The failure that is causing the failure you're seeing actually occurs earlier in the log file while executing a task in the ```pre.cpu_check.yml``` module:

```
2020-05-04 20:28:31,676 p=13766 u=cloud-user n=ansible | fatal: [casTarget]: FAILED! => {
    "assertion": "(cpuinfo.stdout | int) >= (min_cores_num | int)", 
    "changed": false, 
    "evaluated_to": false, 
    "msg": "This server should have at least (8) cores.\nIt only has 4 core(s).\nAdd --skip-tags skipcoresfail to bypass.\n"
}
```
You can see in the log that no further tasks are run against the ```casTarget``` host once the failure above is encountered.

When this happens Ansible just removes the host where the failure occurred from it's list of targeted hosts and moves on with the remaining hosts. In this case, the ```casTarget``` host was dropped so when it reached the shortname check, it never ran the task to gather the shortname and thus never created the ```hostvars``` key needed for the loop. However, the loop iterates over ```group['sas-all']```, which Ansible treats as a variable, so it uses the literal value defined in the inventory file, which still includes ```casTarget```. Ultimately, this leads to the attempt to access the expected value for ```casTarget```, without it actually being defined. 

Adding the ```--skip-tags skipcorefail``` option to the Ansible invocation should cause the playbook to execute successfully.

**Comment by kevinlinglesas** [comment] 2020-06-01 16:47
Sorry, I hadn't gotten back around to posting details, but my findings were inline with what @sasjowood posted above.   However, I thought @henriquevaskys had changed the default params downward to accommodate the smaller casTarget to avoid needing the skip-tags.  I just hadn't had a chance to re-evaluate to determine if the behavior was different.    @sasjowood are you findings based on re-running or from analysis of earlier logs?

**Comment by sasjowood** [comment] 2020-06-01 17:21
@kevinlinglesas, they're based on the log posted in the comment from May 4.

**Comment by kevinlinglesas** [comment] 2020-06-01 17:29
@sasjowood I think things have changed since then.   I will try to re-visit this where I left off and post soon with some more details.

**Comment by kevinlinglesas** [comment] 2020-06-01 18:04
When I last looked at this, @henriquevaskys had:

1. deployTarget to viyaTarget in the inventory file

1. changed min_mem_mb (80000 -> 800) and min_cores_num (8 -> 2) in defaults/main.yml

Today I re-executed playbook like so:
```
$ ansible-playbook viya_pre_install_playbook.yml -i pre-install.inventory.ini -vvvv -e use_pause=false | tee -a deployment-20200601.log
```
That log (masking user & customer) is attached.   
[deployment-20200601.log](https://github.com/sassoftware/viya-ark/files/4712734/deployment-20200601.log)

I don't see failures related to memory or cpu anymore in that log, so the skip-tags are not needed.  I do still see failures remaining when trying to ping casTarget.

```
TASK [viya-ark.preinstall : Ping host casTarget from deployment host using gathered shortname] *************************
task path: /opt/sas/sas_viya_playbook/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.short_hostname_check_loop.yml:6
fatal: [viyaTarget]: FAILED! => {
    "msg": "The conditional check 'hostname_results.stdout_lines | length > 0' failed. The error was: error while evaluating conditional (hostname_results.stdout_lines | length > 0): 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'pre_short_hostname_check_results'\n\nThe error appears to be in '/opt/sas/sas_viya_playbook/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.short_hostname_check_loop.yml': line 6, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:\n    - name: \"Ping host {{ host }} from deployment host using gathered shortname\"\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"
}

TASK [viya-ark.preinstall : debug] *************************************************************************************
task path: /opt/sas/sas_viya_playbook/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.short_hostname_check_loop.yml:13
fatal: [viyaTarget]: FAILED! => {
    "msg": "The conditional check 'hostname_results.stdout_lines | length > 0' failed. The error was: error while evaluating conditional (hostname_results.stdout_lines | length > 0): 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'pre_short_hostname_check_results'\n\nThe error appears to be in '/opt/sas/sas_viya_playbook/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.short_hostname_check_loop.yml': line 13, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  rescue:\n    - debug:\n      ^ here\n"
}

NO MORE HOSTS LEFT *****************************************************************************************************

PLAY RECAP *************************************************************************************************************
casTarget                  : ok=28   changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
viyaTarget                 : ok=53   changed=0    unreachable=0    failed=1    skipped=4    rescued=1    ignored=0 
```
The ping'ing of viyaTarget occurs just before the above "fatal:" tasks and appears to be successful.

**Comment by sasjowood** [comment] 2020-06-01 18:25
@kevinlinglesas,

Reviewing the the log you've attached, I'm still seeing failures for ```casTarget``` occurring before the shortname check is reached, albeit they are new failures:

```
failed: [casTarget] (item={'stderr_lines': [], 'ansible_loop_var': u'item', u'end': u'2020-06-01 13:41:09.522402', u'stderr': u'', u'stdout': u'31173', u'changed': False, 'failed': False, u'delta': u'0:00:00.092739', u'cmd': u'df -Ph "/opt/sas" --block-size=M | tail -1 | awk \'{print $4}\' | sed \'s/[^0-9]*\\([0-9]\\+\\)[^0-9]*/\\1/\'', 'item': {'item': {u'path': u'/opt/sas', u'min_storage_mb': 40000, u'permission': 755, u'min_io': 2}, u'stat': {u'charset': u'binary', u'uid': 1001, u'exists': True, u'attr_flags': u'', u'woth': False, u'device_type': 0, u'mtime': 1578771844.0, u'block_size': 4096, u'inode': 46137984, u'isgid': False, u'size': 64, u'executable': True, u'roth': True, u'isuid': False, u'readable': True, u'isreg': False, u'version': u'961248272', u'pw_name': u'sas', u'gid': 1001, u'ischr': False, u'wusr': True, u'writeable': True, u'isdir': True, u'blocks': 0, u'xoth': True, u'rusr': True, u'nlink': 5, u'issock': False, u'rgrp': True, u'gr_name': u'sas', u'path': u'/opt/sas', u'xusr': True, u'atime': 1588280743.3978906, u'mimetype': u'inode/directory', u'ctime': 1588246016.691657, u'isblk': False, u'xgrp': True, u'dev': 64769, u'wgrp': False, u'isfifo': False, u'mode': u'0755', u'islnk': False, u'attributes': []}, 'ansible_loop_var': u'item', 'failed': False, u'invocation': {u'module_args': {u'follow': False, u'get_checksum': True, u'path': u'/opt/sas', u'checksum_algorithm': u'sha1', u'get_md5': False, u'get_mime': True, u'get_attributes': True}}, u'changed': False}, u'rc': 0, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'strip_empty_ends': True, u'_raw_params': u'df -Ph "/opt/sas" --block-size=M | tail -1 | awk \'{print $4}\' | sed \'s/[^0-9]*\\([0-9]\\+\\)[^0-9]*/\\1/\'', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin_add_newline': True, u'stdin': None}}, 'stdout_lines': [u'31173'], u'start': u'2020-06-01 13:41:09.429663'}) => {
    "ansible_loop_var": "item", 
    "assertion": "(item.stdout | int) >= (item.item.item.min_storage_mb | int)", 
    "changed": false, 
    "evaluated_to": false, 
    "item": {
        "ansible_loop_var": "item", 
        "changed": false, 
        "cmd": "df -Ph \"/opt/sas\" --block-size=M | tail -1 | awk '{print $4}' | sed 's/[^0-9]*\\([0-9]\\+\\)[^0-9]*/\\1/'", 
        "delta": "0:00:00.092739", 
        "end": "2020-06-01 13:41:09.522402", 
        "failed": false, 
        "invocation": {
            "module_args": {
                "_raw_params": "df -Ph \"/opt/sas\" --block-size=M | tail -1 | awk '{print $4}' | sed 's/[^0-9]*\\([0-9]\\+\\)[^0-9]*/\\1/'", 
                "_uses_shell": true, 
                "argv": null, 
                "chdir": null, 
                "creates": null, 
                "executable": null, 
                "removes": null, 
                "stdin": null, 
                "stdin_add_newline": true, 
                "strip_empty_ends": true, 
                "warn": true
            }
        }, 
        "item": {
            "ansible_loop_var": "item", 
            "changed": false, 
            "failed": false, 
            "invocation": {
                "module_args": {
                    "checksum_algorithm": "sha1", 
                    "follow": false, 
                    "get_attributes": true, 
                    "get_checksum": true, 
                    "get_md5": false, 
                    "get_mime": true, 
                    "path": "/opt/sas"
                }
            }, 
            "item": {
                "min_io": 2, 
                "min_storage_mb": 40000, 
                "path": "/opt/sas", 
                "permission": 755
            }, 
            "stat": {
                "atime": 1588280743.3978906, 
                "attr_flags": "", 
                "attributes": [], 
                "block_size": 4096, 
                "blocks": 0, 
                "charset": "binary", 
                "ctime": 1588246016.691657, 
                "dev": 64769, 
                "device_type": 0, 
                "executable": true, 
                "exists": true, 
                "gid": 1001, 
                "gr_name": "sas", 
                "inode": 46137984, 
                "isblk": false, 
                "ischr": false, 
                "isdir": true, 
                "isfifo": false, 
                "isgid": false, 
                "islnk": false, 
                "isreg": false, 
                "issock": false, 
                "isuid": false, 
                "mimetype": "inode/directory", 
                "mode": "0755", 
                "mtime": 1578771844.0, 
                "nlink": 5, 
                "path": "/opt/sas", 
                "pw_name": "sas", 
                "readable": true, 
                "rgrp": true, 
                "roth": true, 
                "rusr": true, 
                "size": 64, 
                "uid": 1001, 
                "version": "961248272", 
                "wgrp": false, 
                "woth": false, 
                "writeable": true, 
                "wusr": true, 
                "xgrp": true, 
                "xoth": true, 
                "xusr": true
            }
        }, 
        "rc": 0, 
        "start": "2020-06-01 13:41:09.429663", 
        "stderr": "", 
        "stderr_lines": [], 
        "stdout": "31173", 
        "stdout_lines": [
            "31173"
        ]
    }, 
    "msg": "The directory /opt/sas only has 31.173 GB of free space.\nIt should have at least 40.0 GB.\nEdit the storage_list variable if this is a mistake.\nOr add --skip-tags skipstoragefail to bypass.\n"
}
```

and

```
failed: [casTarget] (item={'stderr_lines': [], 'ansible_loop_var': u'item', u'end': u'2020-06-01 13:41:11.924953', u'stderr': u'', u'stdout': u'31173', u'changed': False, 'failed': False, u'delta': u'0:00:00.087145', u'cmd': u'df -Ph "/opt" --block-size=M | tail -1 | awk \'{print $4}\' | sed \'s/[^0-9]*\\([0-9]\\+\\)[^0-9]*/\\1/\'', 'item': {'item': {u'path': u'/opt', u'min_storage_mb': 40000, u'permission': 755, u'min_io': 2}, u'stat': {u'charset': u'binary', u'uid': 0, u'exists': True, u'attr_flags': u'', u'woth': False, u'device_type': 0, u'mtime': 1588056503.905296, u'block_size': 4096, u'inode': 12583037, u'isgid': False, u'size': 17, u'executable': True, u'roth': True, u'isuid': False, u'readable': True, u'isreg': False, u'version': u'18446744071940412423', u'pw_name': u'root', u'gid': 0, u'ischr': False, u'wusr': True, u'writeable': True, u'isdir': True, u'blocks': 0, u'xoth': True, u'rusr': True, u'nlink': 3, u'issock': False, u'rgrp': True, u'gr_name': u'root', u'path': u'/opt', u'xusr': True, u'atime': 1588243690.1750488, u'mimetype': u'inode/directory', u'ctime': 1588056503.905296, u'isblk': False, u'xgrp': True, u'dev': 64769, u'wgrp': False, u'isfifo': False, u'mode': u'0755', u'islnk': False, u'attributes': []}, 'ansible_loop_var': u'item', 'failed': False, u'invocation': {u'module_args': {u'follow': False, u'get_checksum': True, u'path': u'/opt', u'checksum_algorithm': u'sha1', u'get_md5': False, u'get_mime': True, u'get_attributes': True}}, u'changed': False}, u'rc': 0, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'strip_empty_ends': True, u'_raw_params': u'df -Ph "/opt" --block-size=M | tail -1 | awk \'{print $4}\' | sed \'s/[^0-9]*\\([0-9]\\+\\)[^0-9]*/\\1/\'', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin_add_newline': True, u'stdin': None}}, 'stdout_lines': [u'31173'], u'start': u'2020-06-01 13:41:11.837808'}) => {
    "ansible_loop_var": "item", 
    "assertion": "(item.stdout | int) >= (item.item.item.min_storage_mb | int)", 
    "changed": false, 
    "evaluated_to": false, 
    "item": {
        "ansible_loop_var": "item", 
        "changed": false, 
        "cmd": "df -Ph \"/opt\" --block-size=M | tail -1 | awk '{print $4}' | sed 's/[^0-9]*\\([0-9]\\+\\)[^0-9]*/\\1/'", 
        "delta": "0:00:00.087145", 
        "end": "2020-06-01 13:41:11.924953", 
        "failed": false, 
        "invocation": {
            "module_args": {
                "_raw_params": "df -Ph \"/opt\" --block-size=M | tail -1 | awk '{print $4}' | sed 's/[^0-9]*\\([0-9]\\+\\)[^0-9]*/\\1/'", 
                "_uses_shell": true, 
                "argv": null, 
                "chdir": null, 
                "creates": null, 
                "executable": null, 
                "removes": null, 
                "stdin": null, 
                "stdin_add_newline": true, 
                "strip_empty_ends": true, 
                "warn": true
            }
        }, 
        "item": {
            "ansible_loop_var": "item", 
            "changed": false, 
            "failed": false, 
            "invocation": {
                "module_args": {
                    "checksum_algorithm": "sha1", 
                    "follow": false, 
                    "get_attributes": true, 
                    "get_checksum": true, 
                    "get_md5": false, 
                    "get_mime": true, 
                    "path": "/opt"
                }
            }, 
            "item": {
                "min_io": 2, 
                "min_storage_mb": 40000, 
                "path": "/opt", 
                "permission": 755
            }, 
            "stat": {
                "atime": 1588243690.1750488, 
                "attr_flags": "", 
                "attributes": [], 
                "block_size": 4096, 
                "blocks": 0, 
                "charset": "binary", 
                "ctime": 1588056503.905296, 
                "dev": 64769, 
                "device_type": 0, 
                "executable": true, 
                "exists": true, 
                "gid": 0, 
                "gr_name": "root", 
                "inode": 12583037, 
                "isblk": false, 
                "ischr": false, 
                "isdir": true, 
                "isfifo": false, 
                "isgid": false, 
                "islnk": false, 
                "isreg": false, 
                "issock": false, 
                "isuid": false, 
                "mimetype": "inode/directory", 
                "mode": "0755", 
                "mtime": 1588056503.905296, 
                "nlink": 3, 
                "path": "/opt", 
                "pw_name": "root", 
                "readable": true, 
                "rgrp": true, 
                "roth": true, 
                "rusr": true, 
                "size": 17, 
                "uid": 0, 
                "version": "18446744071940412423", 
                "wgrp": false, 
                "woth": false, 
                "writeable": true, 
                "wusr": true, 
                "xgrp": true, 
                "xoth": true, 
                "xusr": true
            }
        }, 
        "rc": 0, 
        "start": "2020-06-01 13:41:11.837808", 
        "stderr": "", 
        "stderr_lines": [], 
        "stdout": "31173", 
        "stdout_lines": [
            "31173"
        ]
    }, 
    "msg": "The directory /opt only has 31.173 GB of free space.\nIt should have at least 40.0 GB.\nEdit the storage_list variable if this is a mistake.\nOr add --skip-tags skipstoragefail to bypass.\n"
}
```

The behavior is the same as displayed in the original log where the ```casTarget``` host is dropped and no task after these failures runs against the ```casTarget``` host.

**Comment by kevinlinglesas** [comment] 2020-06-01 18:31
@sasjowood, sorry I missed those :/   didn't search for other than "fatal:"   I concur then with what your analysis is.  It's the same scenario:  1) some failure wrt a given host and 2) subsequent dropping of that host for other tasks later in the playbook.  

Therefore, this is expected per normal Ansible behavior.

**Comment by kevinlinglesas** [comment] 2020-06-03 13:25
So I think we have covered this issue at this point, so I am closing.

**Closed by kevinlinglesas** 2020-06-03 13:25 UTC
