### ISSUE TITLE
missing pam_limits module

### ISSUE THREAD

**Issue by smxall** [sassoftware/viya-ark#105] opened 2023-09-22 00:21 UTC
**Describe the bug**
lauching viya_preinstall_playbook with check option, I get the following error:

ERROR! couldn't resolve module/action 'pam_limits'. This often indicates a misspelling, missing collection, or incorrect module path.

If we launch with the skip-tags option, I have the same ERROR message.

We noticed ansible community.general install was missing, but, even installing community general module, I get the same ERROR

**Environment**
- [ ] Ansible version: 7.7.0
- [ ] Ansible Core: 2.14.10
- [ ] Python version: 3.11
- [ ] OS version: RHLH 8.8
- [ ] Failed playbook tasks log (or entire playbook log) [Attach] pre-install-playbook
- [ ] What version of Viya 3.x is being deployed? 3.5

**To Reproduce**
1. Firstly, ...
2. Then, ...
3. 

**Expected behavior**
[viya-ark.log](https://github.com/sassoftware/viya-ark/files/12694339/viya-ark.log)

**Comment by smxall** [comment] 2023-09-22 00:27
I forget to say, reviwing all modules, the related module ulimit_config is installed, that makes mucho more wird the error Im geting.

**Comment by erharb** [comment] 2023-09-22 13:25
Can you please try running without the check mode enabled?

**Comment by erharb** [comment] 2023-09-22 20:47
I was able to reproduce the problem, apparently it's pretty easy to get into a state where ansible and ansible-core aren't installed properly. I started by installing ansible-core before ansible using the pipx method and saw the same error:

```bash
pipx install --include-deps ansible-core==2.14.10
pipx install --include-deps ansible==7.7.0

ansible-playbook ./playbooks/pre-install-playbook/viya_pre_install_playbook.yml -i ./playbooks/pre-install-playbook/pre-install.inventory.ini --check
ERROR! couldn't resolve module/action 'pam_limits'. This often indicates a misspelling, missing collection, or incorrect module path.
...
```

However, according to the doc you should only need to run the command to install the correct version of ansible and it will do the right thing. 

https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html

So I removed both ansible and ansible-core to start over, then installed only ansible, which then worked:

```bash
pipx uninstall ansible
pipx uninstall ansible-core

pipx install --include-deps ansible==7.7.0

ansible-playbook ./playbooks/pre-install-playbook/viya_pre_install_playbook.yml -i ./playbooks/pre-install-playbook/pre-install.inventory.ini --check

PLAY [localhost] *************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************
ok: [localhost]
...
```

**Comment by kevinlinglesas** [comment] 2023-09-22 21:43
I too tried to reproduce this, but I installed ansible 7.7.0 (not ansible-core separately) and was not able to reproduce the error.  Thankfully, @erharb took a different route and gained the necessary insight.

**Comment by kevinlinglesas** [comment] 2023-09-27 16:54
closing this issue as the reported issue is not directly related to viya-ark project.

**Closed by kevinlinglesas** 2023-09-27 16:54 UTC
