### ISSUE TITLE
Failed to run deployment report

### ISSUE THREAD

**Issue by kurthaemmerle** [sassoftware/viya-ark#63] opened 2020-07-15 16:24 UTC
TASK [Process SAS host details] **************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'sasnote'
fatal: [ViyaNode -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1594829820.94-163151177864278/AnsiballZ_process_sas_host_details.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1594829820.94-163151177864278/AnsiballZ_process_sas_host_details.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1594829820.94-163151177864278/AnsiballZ_process_sas_host_details.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.process_sas_host_details', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_process_sas_host_details_payload_CSWVDT/ansible_process_sas_host_details_payload.zip/ansible/modules/process_sas_host_details.py\", line 833, in <module>\n  File \"/tmp/ansible_process_sas_host_details_payload_CSWVDT/ansible_process_sas_host_details_payload.zip/ansible/modules/process_sas_host_details.py\", line 799, in main\nKeyError: 'sasnote'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by kevinlinglesas** [comment] 2020-07-15 17:06
Hi @kurthaemmerle, can you provide some additional information?

- What version of Viya are you using?
- What version of Ansible are you using?
- What OS version is in the deployment?
- Some details of the deployment env (eg, single vs. multi machine).
- How the playbook was executed (eg, options passed and such)?
- Full log?

**Comment by kurthaemmerle** [comment] 2020-07-15 17:43
Hi,

please find my comments below 😊.
Hope that helps, otherwise let me know if you need more information.
By the way I do use latest version of (viya-ark-master) today downloaded.

Thanks in advance and regards,
Kurt

Kurt Hämmerle
Senior Pre-Sales Technical Architect ▪ Pre-Sales Services DACH
Tel: +41 44 805 74 67 ▪ Mobile: +41 79 745 16 53 ▪ kurt.haemmerle@sas.com
SAS Institute AG ▪ Richtistrasse 11 ▪ CH-8304 Wallisellen
www.sas.com/ch
SAS® … THE POWER TO KNOW®

Von: kevinlinglesas <notifications@github.com>
Gesendet: Mittwoch, 15. Juli 2020 19:07
An: sassoftware/viya-ark <viya-ark@noreply.github.com>
Cc: Kurt Hämmerle <kurt.haemmerle@sas.com>; Mention <mention@noreply.github.com>
Betreff: Re: [sassoftware/viya-ark] Failed to run deployment report (#63)


EXTERNAL

Hi @kurthaemmerle<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkurthaemmerle&data=02%7C01%7Ckurt.haemmerle%40sas.com%7Cd3c1d87632574d336a5908d828e18092%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C637304296288162891&sdata=esHaSOgp7chj1xjphnOqB982cyotyWZRH6ZqX8yjRHo%3D&reserved=0>, can you provide some additional information?

  *   What version of Viya are you using?
Viya 3.5


  *   What version of Ansible are you using?
ansible 2.9.2
  config file = /opt/sas/sasinstall/sas_viya_playbook/ansible.cfg
  configured module search path = [u'/opt/sas/sasinstall/sas_viya_playbook/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]


  *   What OS version is in the deployment?
CentOS Linux release 7.7.1908 (Core)


  *   Some details of the deployment env (eg, single vs. multi machine).
MPP with 8 machines

(inventory.ini)
ViyaNode   ansible_host=gr10pocps01.vsp.sas.com ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa consul_bind_adapter=ens224 internal_deployment_ipv4_override=10.255.32.3 self_deployment_ipv4_override=127.0.0.1
CASWorker1 ansible_host=gr10pocps02.vsp.sas.com ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa consul_bind_adapter=ens224 internal_deployment_ipv4_override=10.255.32.4 self_deployment_ipv4_override=127.0.0.1
CASWorker2 ansible_host=gr10pocps03.vsp.sas.com ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa consul_bind_adapter=ens224 internal_deployment_ipv4_override=10.255.32.5 self_deployment_ipv4_override=127.0.0.1
CASWorker3 ansible_host=gr10pocps04.vsp.sas.com ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa consul_bind_adapter=ens224 internal_deployment_ipv4_override=10.255.32.6 self_deployment_ipv4_override=127.0.0.1
CASWorker4 ansible_host=gr10pocps05.vsp.sas.com ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa consul_bind_adapter=ens224 internal_deployment_ipv4_override=10.255.32.7 self_deployment_ipv4_override=127.0.0.1
CASWorker5 ansible_host=gr10pocps06.vsp.sas.com ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa consul_bind_adapter=ens224 internal_deployment_ipv4_override=10.255.32.8 self_deployment_ipv4_override=127.0.0.1
CASWorker6 ansible_host=gr10pocps07.vsp.sas.com ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa consul_bind_adapter=ens224 internal_deployment_ipv4_override=10.255.32.9 self_deployment_ipv4_override=127.0.0.1
CASWorker7 ansible_host=gr10pocps08.vsp.sas.com ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa consul_bind_adapter=ens224 internal_deployment_ipv4_override=10.255.32.10 self_deployment_ipv4_override=127.0.0.1


  *   How the playbook was executed (eg, options passed and such)?
ansible-playbook viya-deployment-report.yml -i /opt/sas/sasinstall/sas_viya_playbook/inventory.ini -e "include_package_files=true"


  *   Full log?
Only what i did provide in the issue
If you need more, then I could run the playbook with -vvv ?

**Comment by kevinlinglesas** [comment] 2020-07-16 13:47
If you do happen to run it again, then yet, -vvv would be good.  I don't think you need to re-run at this point.  My automation reproduced this same issue.

**Comment by kurthaemmerle** [comment] 2020-07-16 14:14
Hi, if you did reproduce the same issue then it would be great if I can get a fix for it 😊
Thanks and Regards,
Kurt

Von: kevinlinglesas <notifications@github.com>
Gesendet: Donnerstag, 16. Juli 2020 15:48
An: sassoftware/viya-ark <viya-ark@noreply.github.com>
Cc: Kurt Hämmerle <kurt.haemmerle@sas.com>; Mention <mention@noreply.github.com>
Betreff: Re: [sassoftware/viya-ark] Failed to run deployment report (#63)


EXTERNAL

If you do happen to run it again, then yet, -vvv would be good. I don't think you need to re-run at this point. My automation reproduced this same issue.

**Comment by erharb** [comment] 2020-07-16 14:47
To workaround while we identify the root cause and the fix you can disable the hotfix report section adding the following param to the ansible-playbook command to run the deployment report:
`-e "include_hotfix_report=False"`

**Comment by kurthaemmerle** [comment] 2020-07-16 15:08
Hi Eric, that works fine, but the Hotfix Report is the interesting thing.
Meanwhile I can live with that and waiting for an fix, thanks.
Cheers
Kurt

Von: Eric Harbeston <notifications@github.com>
Gesendet: Donnerstag, 16. Juli 2020 16:48
An: sassoftware/viya-ark <viya-ark@noreply.github.com>
Cc: Kurt Hämmerle <kurt.haemmerle@sas.com>; Mention <mention@noreply.github.com>
Betreff: Re: [sassoftware/viya-ark] Failed to run deployment report (#63)


EXTERNAL

To workaround while we identify the root cause and the fix you can disable the hotfix report section adding the following param to the ansible-playbook command to run the deployment report:
-e "include_hotfix_report=False"

**Comment by erharb** [comment] 2020-08-06 19:32
Sorry for the late notice but this was fixed with the most recent release just over a week ago:
https://github.com/sassoftware/viya-ark/blob/master/CHANGELOG.md#viya35-ark-17---july-29-2020

- SAS Viya Deployment Report
  - VIYAARK-207 - Deployment Report not working when including hotfixes.

**Closed by erharb** 2020-08-06 19:32 UTC

**Comment by kurthaemmerle** [comment] 2020-08-10 12:49
Hi Eric,
thanks a lot its working fine now 😊
Cheers
Kurt

Kurt Hämmerle
Senior Pre-Sales Technical Architect ▪ Pre-Sales Services DACH
Tel: +41 44 805 74 67 ▪ Mobile: +41 79 745 16 53 ▪ kurt.haemmerle@sas.com
SAS Institute AG ▪ Richtistrasse 11 ▪ CH-8304 Wallisellen
www.sas.com/ch
SAS® … THE POWER TO KNOW®

Von: Eric Harbeston <notifications@github.com>
Gesendet: Donnerstag, 6. August 2020 21:33
An: sassoftware/viya-ark <viya-ark@noreply.github.com>
Cc: Kurt Hämmerle <kurt.haemmerle@sas.com>; Mention <mention@noreply.github.com>
Betreff: Re: [sassoftware/viya-ark] Failed to run deployment report (#63)


EXTERNAL

Sorry for the late notice but this was fixed with the most recent release just over a week ago:
https://github.com/sassoftware/viya-ark/blob/master/CHANGELOG.md#viya35-ark-17---july-29-2020<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsassoftware%2Fviya-ark%2Fblob%2Fmaster%2FCHANGELOG.md%23viya35-ark-17---july-29-2020&data=02%7C01%7Ckurt.haemmerle%40sas.com%7C339a78f921094fde1fcd08d83a3f86d6%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C637323391800799813&sdata=DZhtWXgWhR3EU39zELY53KKl%2Fm83aaqYWPEVL9eDc9M%3D&reserved=0>

  *   SAS Viya Deployment Report

     *   VIYAARK-207 - Deployment Report not working when including hotfixes.
