### ISSUE TITLE
Remove SAS CAS Worker of playbook

### ISSUE THREAD

**Issue by cristianmarl** [sassoftware/viya-ark#59] opened 2020-05-28 09:50 UTC
Hi,
I'm trying to remove a CAS Worker but when I run the Ansible start script the log write an error in TASK  TASK [SAS Infrastructure Data Server - postgres]:
"ERROR: consul is not healthy, please check consul log."

I have changed the inventory.ini to remove one CAS Worker definition but I don't know if it's necesary to change another configuration file.

Thanks

**Comment by erharb** [comment] 2020-05-28 12:41
Is consul running and healthy on each server?

**Comment by cristianmarl** [comment] 2020-06-01 05:32
The CAS Worker Machine is sign off. I've only changed the inventory.ini commenting the lines of CAS Worker that I need to remove.
If I run the Ansible to start, I have the message: "ERROR: consul is not healthy, please check consul log.".
Surely, I need to change another config file, but I don't find it.

The steps I do:
1. I configure SAS Environment Manager to remove CAS Worker 4.
2. I stop CAS Worker 4 with scripts
3. I sign off CAS Worker 4 server
4. I comment lines of inventory.ini of CAS Worker 4

When I need to restart all platform (excluding CAS Worker 4) I have the error.

**Comment by erharb** [comment] 2020-06-01 14:37
The error wouldn't appear to be related to the removal of the CAS worker, most likely an issue between consul and postgres which may be one of the few issues related to that we fixed in the new release just a few days ago. I would recommend trying the new release and then let us know if the problem is still in play and we can go from there.

https://github.com/sassoftware/viya-ark/releases

**Comment by cristianmarl** [comment] 2020-06-02 06:09
Thanks.

I review it.

Un saludo,
Cristian Martín Loriente
Consultor Senior
Teléfono: 650 20 97 39, Ext.: 2080
[Innova-tsn]<http://www.innova-tsn.com/>

MADRID
C/ Orense, 4, 5 Planta - 28020 Madrid<https://goo.gl/maps/22xqwDz8HeC2>
Plaza Gómez Moreno, 2, 17 Planta - 28020 Madrid<https://goo.gl/maps/Fg2V5NvNu7D2>
Tel. +34915130073

BARCELONA
Av. Diagonal, 453 bis, 6º Planta - 08036 Barcelona<https://goo.gl/maps/CZeC5EbqUem>
Tel. +34932776926

LONDRES
Suite 609, 107 Cheapside City of London EC2V 6DN<https://goo.gl/maps/Vt6YnqNCAjk>
Tel. +442073972812

www.innova-tsn.com<http://www.innova-tsn.com/>

[cid:image002.png@01D638B5.4CC715C0]<https://www.linkedin.com/company/innovatsn/?originalSubdomain=es> [cid:image003.png@01D638B5.4CC715C0] <https://twitter.com/innovatsn?lang=es>    [cid:image004.png@01D638B5.4CC715C0] <https://www.youtube.com/channel/UCnhhzy6vkYEtSoRSwMAq54Q>

CONFIDENCIALIDAD La información contenida en este correo electrónico es confidencial/privilegiada y está destinada a ser leída sólo por la(s) persona (s a la(s) que va dirigida. Si usted lee este documento y no es el destinatario señalado, o ha recibido esta comunicación por error, le informamos de que está totalmente prohibida y puede ser ilegal cualquier divulgación, distribución o reproducción de esta comunicación, le rogamos que nos lo notifique inmediatamente elimine dicho correo de su equipo. En el caso de ser el destinatario del mismo no podrá usarlo para fines distintos a los de la propia comunicación que contiene, ni tampoco ser utilizado en juicio (artículo 34.e) de RD 58/2001 de 22 de abril, por el que se aprueba el Estatuto General de la Abogacía Española).


De: Eric Harbeston <notifications@github.com>
Enviado el: lunes, 1 de junio de 2020 16:38
Para: sassoftware/viya-ark <viya-ark@noreply.github.com>
CC: Cristian Martín Loriente <cristian.martin@innova-tsn.com>; Author <author@noreply.github.com>
Asunto: Re: [sassoftware/viya-ark] Remove SAS CAS Worker of playbook (#59)


The error wouldn't appear to be related to the removal of the CAS worker, most likely an issue between consul and postgres which may be one of the few issues related to that we fixed in the new release just a few days ago. I would recommend trying the new release and then let us know if the problem is still in play and we can go from there.

https://github.com/sassoftware/viya-ark/releases

**Comment by erharb** [comment] 2020-09-25 18:10
Sorry for the long delay, are you still having this issue or were you already able to make it past?

I'm thinking if xxxxxx048 no longer has any SAS services running on it, since that is the one being removed as CAS worker, it should be removed from the inventory file altogether to avoid communication with it.

**Comment by erharb** [comment] 2021-01-08 18:20
Since there has been no further response I assume my last comment is the reason. Please make sure your inventory file represents the actual up to date machine topology before using Viya ARK.

**Closed by erharb** 2021-01-08 18:20 UTC
