### ISSUE TITLE
Set valid installed package flag failing to compare correctly

### ISSUE THREAD

**Issue by aekuback** [sassoftware/viya-ark#61] opened 2020-06-10 20:28 UTC
In the task to compare require packages nss and curl, the Viya-ARK is failing with a error like the one below:

TASK [viya-ark.preinstall : Set valid installed package flag] ********************************************************************************************************************************
fatal: [deployTarget]: FAILED! => {"msg": "The conditional check 'installed_package.rc == 0 and installed_package_version.stdout is version_compare(item.value, '>=')' failed. The error was: Version comparison: '<' not supported between instances of 'str' and 'int'\n\nThe error appears to be in '/home/viyadep/ark/viya-ark-master/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.package_version_check.yml': line 38, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Set valid installed package flag\n    ^ here\n"}

We manually confirmed both packages are valid but the Viya-ARK fails here without an option to move on.  We are running in check mode.  

Ansible version 2.9.9
RHEL 7.8
Viya 3.5
Latest Public Ship.

**Comment by kevinlinglesas** [comment] 2020-06-15 13:22
Attempting to Re-Produce https://github.com/sassoftware/viya-ark/issues/61

Environment Information from Issue Submission:
- Executing pre.package_version_check.yml "Set valid installed package flag" task.
- Ansible version 2.9.9
- RHEL 7.8
- Viya 3.5
- Viya ARK version: "Latest Public Ship" 
  - which would be https://github.com/sassoftware/viya-ark/releases/tag/Viya35-ark-1.5 
    or master cloned around 6/9-10/2020.

There was no additional context of where execution was in the pre.package_version_check 
in terms of whether it was checking the version of curl or nss.  These are the required_package_versions_rhel
settings currently used:
	required_package_versions_rhel:
		- { name: curl, value: 7.19.7-53 }
		- { name: nss.x86_64, value: 3.36.0-7 }
		
		
My OpenStack tenant & region does not have an explicit RHEL 7.8 image available.
I installed RHEL 7.7 and the updated to RHEL 7.8.

$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"

$ sudo yum update
. . .
Replaced:
  iwl7265-firmware.noarch 0:22.0.7.0-72.el7

Complete!
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.8 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.8"


The versions of curl and nss packages installed before and after updating to 7.8 were above the requried minimums.
RHEL 7.7
$ sudo yum list installed curl
. . .
Installed Packages
curl.x86_64                                    7.29.0-54.el7_7.1                                    @sasit-rhel7-server
$ sudo yum list installed nss.x86_64
. . .
Installed Packages
nss.x86_64                                      3.44.0-7.el7_7                                      @sasit-rhel7-server

RHEL 7.8
$ sudo yum list installed curl                                             
. . .
Installed Packages
curl.x86_64                                      7.29.0-57.el7                                      @sasit-rhel7-server
$ sudo yum list installed nss.x86_64  
. . .
Installed Packages
nss.x86_64                                      3.44.0-7.el7_7                                      @sasit-rhel7-server


Ansible 2.9.9 needs to be installed to match customer environment.
$ sudo pip install ansible=="2.9.9"
Collecting ansible==2.9.9
. . .
Successfully installed ansible-2.9.9 cffi-1.14.0 cryptography-2.9.2 enum34-1.1.10 pycparser-2.20
$ ansible --version
ansible 2.9.9
  config file = None
  configured module search path = [u'/home/cloud-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]


Git was installed to facilitate cloning viya-ark repo.
$ sudo yum install -y git
. . .
Complete!


Github viya-ark repo is cloned and tested.

$ git clone https://github.com/sassoftware/viya-ark.git viya-ark-github
Cloning into 'viya-ark-github'...
remote: Enumerating objects: 704, done.
remote: Counting objects: 100% (704/704), done.
remote: Compressing objects: 100% (314/314), done.
remote: Total 1604 (delta 401), reused 578 (delta 350), pack-reused 900
Receiving objects: 100% (1604/1604), 568.73 KiB | 0 bytes/s, done.
Resolving deltas: 100% (890/890), done.


Executing pre-install playbook for package_version_check tasks only and in check mode

$ cd viya-ark-github/playbooks/pre-install-playbook/
$ ansible-playbook viya_pre_install_playbook.yml -i pre-install.inventory.ini -e use_pause=false -t package_version_check --check

PLAY [localhost] ******************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************
ok: [localhost]

PLAY [sas_all] ********************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************
ok: [deployTarget]

TASK [viya-ark.preinstall : WARNING: If you are running this playbook without the --check parameter, it WILL perform changes to your systems.] ***
skipping: [deployTarget]

TASK [viya-ark.preinstall : Run tasks to check version of available required package] *********************************
included: /home/cloud-user/viya-ark-github/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.package_version_check.yml for deployTarget
included: /home/cloud-user/viya-ark-github/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.package_version_check.yml for deployTarget

TASK [viya-ark.preinstall : Default valid installed package flag to false] ********************************************
ok: [deployTarget]

TASK [viya-ark.preinstall : Check for installed RHEL package 'curl'] **************************************************
ok: [deployTarget]

TASK [viya-ark.preinstall : Check that installed RHEL package 'curl' meets minimum version 7.19.7-53] *****************
ok: [deployTarget]

TASK [viya-ark.preinstall : Set valid installed package flag] *********************************************************
ok: [deployTarget]

TASK [viya-ark.preinstall : Check that required RHEL package 'curl' is available in a repository at some version] *****
skipping: [deployTarget]

TASK [viya-ark.preinstall : Assert that package 'curl' is available] **************************************************
skipping: [deployTarget]

TASK [viya-ark.preinstall : Check that required RHEL package curl is available in some repository at minimum version 7.19.7-53] ***
skipping: [deployTarget]

TASK [viya-ark.preinstall : Assert that available package 'curl' meets the version requirement 7.19.7-53] *************
skipping: [deployTarget]

TASK [viya-ark.preinstall : Default valid installed package flag to false] ********************************************
ok: [deployTarget]

TASK [viya-ark.preinstall : Check for installed RHEL package 'nss.x86_64'] ********************************************
ok: [deployTarget]

TASK [viya-ark.preinstall : Check that installed RHEL package 'nss.x86_64' meets minimum version 3.36.0-7] ************
ok: [deployTarget]

TASK [viya-ark.preinstall : Set valid installed package flag] *********************************************************
ok: [deployTarget]

TASK [viya-ark.preinstall : Check that required RHEL package 'nss.x86_64' is available in a repository at some version] ***
skipping: [deployTarget]

TASK [viya-ark.preinstall : Assert that package 'nss.x86_64' is available] ********************************************
skipping: [deployTarget]

TASK [viya-ark.preinstall : Check that required RHEL package nss.x86_64 is available in some repository at minimum version 3.36.0-7] ***
skipping: [deployTarget]

TASK [viya-ark.preinstall : Assert that available package 'nss.x86_64' meets the version requirement 3.36.0-7] ********
skipping: [deployTarget]

PLAY RECAP ************************************************************************************************************
deployTarget               : ok=11   changed=0    unreachable=0    failed=0    skipped=9    rescued=0    ignored=0
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

No failure seen.

Also re-ran full playbook in check mode.   Still no failure.


The error reported is one that can occur with Python 3.    I asked what version of python was used and it was reported to be 2.7.5.
The output of 'ansible --version' would confirm what version of python is being used by ansible.   Not doubting 2.7.5, but just saying
there can be some confusion.   For example...
$ python --version
Python 2.7.5
$ ansible --version
ansible 2.9.9
  config file = None
  configured module search path = ['/home/cloud-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Sep 26 2019, 11:57:09) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

This is a scenario where ansible was installed with pip3 vs pip and results in python3 being used by ansible.   
I bring all of this up only because, at this point, the only way I've been able to evoke the same failure is in 
the case where ansible is using python3 and I have a test.yml file where I force a type mismatch between version 
information being compared.

$ cat test.yml
- hosts: localhost
  tasks:
  - assert:
      that: "'1.2.3' is version_compare('1.2.2', '>')"
  - assert:
      that: "'1.2.3-pre' is version_compare('1.2.2', '>')"
  - assert:
      that: "'master' is version_compare('master', '>=')"
  - assert:
      that: "'v1.2.3' is version_compare('1.2.2', '>')"
  - assert:
      that: "'master' is version_compare('1.2.2', '>')"


On the 4th and 5th asserts, there will be a type mismatch (str vs. int) and the playbook will fail.
$ ansible-playbook test.yml -i pre-install.inventory.ini

PLAY [localhost] ******************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************
ok: [localhost]

TASK [assert] *********************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [assert] *********************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [assert] *********************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [assert] *********************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check ''v1.2.3' is version_compare('1.2.2', '>')' failed. The error was: Version comparison: '<' not supported between instances of 'str' and 'int'"}

PLAY RECAP ************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0



When I exec this same playbook in env were python 2.7.5 is being used by ansible, there is no failure.

$ ansible --version
ansible 2.9.9
  config file = None
  configured module search path = [u'/home/cloud-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
$ ansible-playbook test.yml -i pre-install.inventory.ini

PLAY [localhost] ******************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************
ok: [localhost]

TASK [assert] *********************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [assert] *********************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [assert] *********************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [assert] *********************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [assert] *********************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY RECAP ************************************************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

$ cat test.yml
- hosts: localhost
  tasks:
  - assert:
      that: "'1.2.3' is version('1.2.2', '>')"
  - assert:
      that: "'1.2.3-pre' is version('1.2.2', '>')"
  - assert:
      that: "'master' is version('master', '>=')"
  - assert:
      that: "'v1.2.3' is version('1.2.2', '>')"
  - assert:
      that: "'master' is version('1.2.2', '>')"


Now, there would also need to be some unexpected difference in the typical version values for curl and/or nss packages
for this failure to occur because in my environment, even with python3 executing with ansible 2.9.9, I was not able to
reproduce the error.   This being the case because the min version of curl and nss and the installed version of these pkgs
do not have incompatible types.    With the information given in the submission I don't know exacty what versions of curl
and nss were installed explicitly - only a statement that both packages were manually confirmed to be valid.
I have no reason to doubt that or course.

Bottomline at this point is that I cannot reproduce the reported error even after attempting, as best I could, to replicate
the customer OS and Ansible version environment.   My reporting of python3 behavior is just offered as a data point for 
a scenario where I was able to evoke the given error.

**Comment by aekuback** [comment] 2020-06-16 16:26
I found out on a different test today that we are using Python 3.6.8 not Python 2.7.5, despite I thought we were.  I was surprised by this.

Alex Kubacki

**Comment by kevinlinglesas** [comment] 2020-06-16 19:11
Email from @aekuback indicated customer was actually using Python3.

`I found out on a different test today that we are using Python 3.6.8 not Python 2.7.5, despite I thought we were. I was surprised by this. `

This could explain the error, but only if the gathered version information is being considered a type mismatch with the control, minimum default version being compared to by the task.   
A request to see if the results of 'yum list installed [curl,nss]' would potentially be helpful.

**Comment by kevinlinglesas** [comment] 2020-09-25 17:53
No further response regarding this issue, so closing.

**Closed by kevinlinglesas** 2020-09-25 17:53 UTC
