### ISSUE TITLE
SAS Viya 3.5 sas-viya-launcher-default service is not stopped by viya-services-stop.yml

### ISSUE THREAD

**Issue by LaimonasReklaitis** [sassoftware/viya-ark#92] opened 2022-10-21 05:55 UTC
2022-10-11 we installed SAS Viya 3.5 on our servers.
2022-10-13 we downloaded and started to use viya-ark-master version (took from https://github.com/sassoftware/viya-ark)

We noticed that with command: 
ansible-playbook viya-ark/playbooks/viya-mmsu/viya-services-stop.yml
all services are shutting down except sas-viya-launcher-default service:

fatal: [compute]: FAILED! => {
    "msg": [
        "Please examine the following stray process(es)",
        "If enable_stray_cleanup=true, process will be cleaned up automatically",
        "except database processes which require fix manually to avoid data corruption.",
        "This playbook can be rerun to clean up the child processes.",
        [
            "sas      3891757       1  0 Oct14 ?        00:02:33 /opt/sas/spre/home/SASFoundation/utilities/bin/launcher --ssl --ssl-certificate /opt/sas/viya/config/etc/SASSecurityCertificateFramework/tls/certs/tklauncher/default/certificate.pem --ssl-private-key /opt/sas/viya/config/etc/SASSecurityCertificateFramework/tls/certs/tklauncher/default/key.pem --ssl-private-key-password /opt/sas/viya/config/etc/SASSecurityCertificateFramework/private/tklauncher/default/key.password --ssl-ca-list /opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts/trustedcerts.pem --hostname ls7a.ls.net --bind-address 0.0.0.0 --registration-port 41523 --sas-services-url https://ls5a.ls.net:443/ --log /opt/sas/viya/config/var/log/tklauncher/default/tklauncher_2022-10-14_08-47-57.log",
            "root     3922505 3891759  0 Oct14 ?        00:00:00 /opt/sas/spre/home/SASFoundation/utilities/bin/sasauth",
            "root     3922509 3891759  0 Oct14 ?        00:00:00 /opt/sas/spre/home/SASFoundation/utilities/bin/sasauth"
        ]
    ]
}

if we use command:
 ansible-playbook viya-ark-master/playbooks/viya-mmsu/viya-services-stop.yml -e "enable_stray_cleanup=true"
then sas-viya-launcher-default service and its processes are cleaned:

ok: [compute] => {
    "msg": [
        "The following stray processes have been cleaned up",
        [
            "sas      3891757       1  0 Oct14 ?        00:02:33 /opt/sas/spre/home/SASFoundation/utilities/bin/launcher --ssl --ssl-certificate /opt/sas/viya/config/etc/SASSecurityCertificateFramework/tls/certs/tklauncher/default/certificate.pem --ssl-private-key /opt/sas/viya/config/etc/SASSecurityCertificateFramework/tls/certs/tklauncher/default/key.pem --ssl-private-key-password /opt/sas/viya/config/etc/SASSecurityCertificateFramework/private/tklauncher/default/key.password --ssl-ca-list /opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts/trustedcerts.pem --hostname ls7a.ls.net --bind-address 0.0.0.0 --registration-port 41523 --sas-services-url https://ls5a.ls.net:443/ --log /opt/sas/viya/config/var/log/tklauncher/default/tklauncher_2022-10-14_08-47-57.log",
            "root     3922505 3891759  0 Oct14 ?        00:00:00 /opt/sas/spre/home/SASFoundation/utilities/bin/sasauth",
            "root     3922509 3891759  0 Oct14 ?        00:00:00 /opt/sas/spre/home/SASFoundation/utilities/bin/sasauth"
        ]
    ]
}

**Environment**
- [ ] Ansible version: core 2.12.2
- [ ] Python version: 3.8.12
- [ ] OS version: RedHat 8.6 x86_64
- [ ] Failed playbook tasks log (or entire playbook log) [Attach]
- [ ] What version of Viya 3.x is being deployed? Viya 3.5

**To Reproduce**
1. Download viya-ark-master from https://github.com/sassoftware/viya-ark
2. Install SAS Viya 3.5
3. Try to stop SAS Viya 3.5 services with command: ansible-playbook viya-ark/playbooks/viya-mmsu/viya-services-stop.yml

**Expected behavior**
We expect all SAS Viya 3.5 services to be stoped with command: ansible-playbook viya-ark/playbooks/viya-mmsu/viya-services-stop.yml
[deployment.log](https://github.com/sassoftware/viya-ark/files/9836072/deployment.log)

**Comment by erharb** [comment] 2022-10-24 13:47
At this time that is the expected behavior of the stop playbook, it is a cautious approach because forcefully stopping services that don't want to be stopped could be a potentially destructive behavior depending on the service. It's purpose is to allow the administrator/user of the system to determine whether it's ok to proceed to kill such processes and is why the parameter exists for `enable_stray_cleanup=true`

**Comment by cuddlehub** [comment] 2022-11-09 15:20
@LaimonasReklaitis Thank you to report the problem.
We have identified the issues and we'll work on the code to improve it.
Thank you and have a nice day!

**Comment by erharb** [comment] 2023-07-28 13:50
This was actually addressed in the May 2023 release, somehow it missed getting in the release notes

https://github.com/sassoftware/viya-ark/releases/tag/Viya35-ark-1.16

**Comment by erharb** [comment] 2023-07-28 15:04
My apologies, it seems the code to fix this somehow got missed in internal merging activities. We'll be correcting this oversight in an upcoming release.

**Comment by kevinlinglesas** [comment] 2023-08-02 18:29
This issue has been addressed in [Release Viya35-ark-1.17](https://github.com/sassoftware/viya-ark/releases/tag/Viya35-ark-1.17)

**Closed by kevinlinglesas** 2023-08-02 18:29 UTC
Labels: bug
