### ISSUE TITLE
Issue with merging SAS Viya Deployment Files Playbook

### ISSUE THREAD

**Issue by AbulHaque** [sassoftware/viya-ark#22] opened 2019-10-02 13:40 UTC
Hi, 
While I run the "merge-viya-deployment-files.yml" with  -vvvv -e "current_inventory_file="my_actual_inventory_file ", I receive the following error:
ERROR! vars file {{ playbook_dir }}/../../../vars.yml was not found on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option

Our ansible version is 2.8.3 and python version is 2.7.5. We will highly appreciate your help in this regard.

**Comment by koicarer** [comment] 2019-10-02 13:54
Can you post a full command that you ran? What is a PWD? Can you attach a copy of the deployment.log that exists on your playbook_dir?

**Comment by koicarer** [comment] 2019-10-02 14:18
It will be worthy to read the README.md that you may find in /<yourfile>/sas_viya_playbook/viya-ark/playbooks/merge-playbook.

**Comment by erharb** [comment] 2019-10-02 14:20
Thanks @koicarer , this is the snippet from the README that directs you to run from your sas_viya_playbook as your PWD (Present Working Directory) because it needs access to the same vars.yml and inventory files used to deploy site.yml.

> To run the playbook, execute the following example command:
> 
> ansible-playbook viya-ark/playbooks/merge-playbook/merge-viya-deployment-files.yml

**Comment by AbulHaque** [comment] 2019-10-03 06:29
Thank you so much for your quick response and suggestions. I ran the playbook from the sas_viya_playbook directory with the following command:
 ansible-playbook viya-ark-Viya34-ark-1.7/playbooks/merge-playbook/merge-viya-deployment-files.yml -vvvv -e "current_inventory_file=/home/viyadep/SAS_Viya_Deployment_update/sas_viya_playbook/inventory.ini"

Afterwards, I received the following error:
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in "/home/viyadep/SAS_Viya_Deployment_update/sas_viya_playbook/viya-ark-Viya34-ark-1.7/playbooks/merge-playbook/merged_files/20191003-074856/vars.yml", line 2, column 1
found duplicate key "SASV9_CONFIGURATION" with value "ordereddict([(1, u'/* set SASWORK to the right location */'), (2, u'WORK=/sastmp/saswork')])" (original value: "None")
  in "/home/viyadep/SAS_Viya_Deployment_update/sas_viya_playbook/viya-ark-Viya34-ark-1.7/playbooks/merge-playbook/merged_files/20191003-074856/vars.yml", line 262, column 1

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.

**Comment by koicarer** [comment] 2019-10-03 12:50
Can you attach a copy of the file /home/viyadep/SAS_Viya_Deployment_update/sas_viya_playbook/vars.yml here?

Thanks,

**Comment by AbulHaque** [comment] 2019-10-07 07:51
Hi, 
Here I attach the vars file.
Thanks in advance!  
[vars.txt](https://github.com/sassoftware/viya-ark/files/3696031/vars.txt)

**Comment by koicarer** [comment] 2019-10-07 14:54
Thanks for the file. I was unable to reproduce the problem with the file that you sent.
I guess more files are needed for me to reproduce the problem. Can you zip the following two folders and send it to me? 

Thank you!

/home/viyadep/SAS_Viya_Deployment_update/sas_viya_playbook/inventory.ini
/home/viyadep/SAS_Viya_Deployment_update/sas_viya_playbook/ansible.cfg
/home/viyadep/SAS_Viya_Deployment_update/sas_viya_playbook/vars.yml

/home/viyadep/SAS_Viya_Deployment_update/sas_viya_playbook/viya-ark-Viya34-ark-1.7/playbooks/merge-playbook/merged_files/20191003-074856

**Comment by kevinlinglesas** [comment] 2019-11-05 15:56
@AbulHaque what is the status of providing more files to aid @koicarer in reproducing this issue?

**Comment by AlissaSchleich** [comment] 2020-05-28 16:47
Closing as not reproducible.

**Closed** 2020-05-28 16:46 UTC
